### ISSUE TITLE
Carga horaria de prof

### ISSUE THREAD

**Issue by jazcarate** [jlavera/mustached-octo-spice#6]
Otro factor muy importante a tener en cuenta es que un profesional no puede tener acumuladas más de 48 horas laborales por semana
    - Ojo esto en la migración
    - En C# creo que se puede arreglar fácil, cada vez que selecciona un item, contamos si tiene 24 => mensaje de error

**Comment by jazcarate** [comment]
ya esta el constraint :) :yum:

**Comment by jlavera** [comment]
Lo abriste y lo cerraste, que careta.

**Comment by jazcarate** [comment]
production value: +inf
